# DS2002 — SQL Challenge Set (Homework)
## Music Streaming Service Database

**Due:** See Canvas  
**Submission:** GitHub

---

In this assignment, you will design and query a relational database for a **music streaming service**.
You will create tables, define primary and foreign keys, insert sample data, and answer analytical questions using SQL.

This homework builds directly on what you learned in:
- SQL Fundamentals in Notebooks (Lecture)
- SQLite + Joins + Grouping (Studio)

Read carefully. This is not a copy-paste exercise.


## Ground Rules (Read First)

- This is a **Kaggle notebook**
- Python cells must contain **valid Python**
- SQL must be executed using the helper function `q(""" SQL HERE """)`
- Do **not** paste raw SQL into a Python cell
- Do **not** use Markdown SQL fences in code cells

If you see `TODO`, you are expected to replace it.


## Part 0 — Setup (Run This Cell)

This cell creates an in-memory SQLite database and helper functions.

In [121]:

import sqlite3
import pandas as pd
from IPython.display import display, Markdown

conn = sqlite3.connect(":memory:")
cur = conn.cursor()

def exec_sql(sql: str):
    cur.executescript(sql)
    conn.commit()

def q(sql: str) -> pd.DataFrame:
    return pd.read_sql_query(sql, conn)

def run_or_todo(sql: str, label: str):
    if "TODO" in sql:
        print(f"{label}: TODO — write the SQL, then re-run this cell.")
        return None
    df = q(sql)
    display(df)
    return df

print("SQLite ready.")

SQLite ready.


## Scenario: Music Streaming Service

You are designing the backend database for a music streaming service.

Users listen to **tracks**, not albums.
Albums group tracks.
Artists release albums.

Hierarchy:
**Artist → Album → Track**
Listening happens at the **Track** level.


## Part 1 — Database Design (DDL)

You must create the following tables:

- `users`
- `artists`
- `albums`
- `tracks`
- `listens`

### Relationship Requirements
- One artist → many albums
- One album → many tracks
- One user ↔ many tracks (via listens)

Create tables with:
- Primary keys
- Foreign keys
- Reasonable data types

Replace all TODOs below.

In [122]:

# TODO: Drop tables if they exist, then CREATE all required tables

exec_sql('''

DROP TABLE IF EXISTS listens;
DROP TABLE IF EXISTS tracks;
DROP TABLE IF EXISTS albums;
DROP TABLE IF EXISTS artists;
DROP TABLE IF EXISTS users;


CREATE TABLE users ( 
    user_id INTERGER PRIMARY KEY, 
    name TEXT NOT NULL 
);

CREATE TABLE artists ( 
    artist_id INTERGER PRIMARY KEY, 
    name TEXT NOT NULL
);

CREATE TABLE albums ( 
    album_id INTERGER PRIMARY KEY, 
    title TEXT NOT NULL, 
    artist_id INTEGER NOT NULL,
    release_year INTEGER, 
    FOREIGN KEY (artist_id) REFERENCES artists(artist_id)
);

CREATE TABLE tracks ( 
    track_id INTERGER PRIMARY KEY, 
    title TEXT NOT NULL, 
    album_id INTEGER NOT NULL,
    duration_seconds INTEGER, 
    FOREIGN KEY (album_id) REFERENCES albums(album_id)
);

CREATE TABLE listens ( 
    listen_id INTEGER PRIMARY KEY,
    user_id INTEGER, 
    track_id INTEGER,
    listen_time TEXT
);

''')

print("Tables created.")

Tables created.


## Part 2 — Insert Sample Data (DML)

Insert **at minimum**:
- 5 users
- 4 artists
- 6 albums
- 15 tracks
- 30 listens

Data should be realistic enough that aggregations are meaningful.

In [123]:

# TODO: Insert sample data into all tables

exec_sql('''

DELETE FROM listens; 
DELETE FROM tracks; 
DELETE FROM albums; 
DELETE FROM artists; 
DELETE FROM users; 



INSERT INTO users (user_id, name) VALUES
(01, "Raymond Santiago"), (02, "Eric Vicente"), (03, "Betzy Flores"), 
(04, "Maria Rivera"), (05, "Camila Nunez"), (06, "Joe Doe");

INSERT INTO artists (artist_id, name) VALUES
(01, "Bad Bunny"), (02, "Lady Gaga"), (03, "Ismael Rivera"), 
(04, "Drake"), (05, "Jowell y Randy");

INSERT INTO albums (album_id, title, artist_id, release_year) VALUES
(01, "Nadie sabe lo que va pasar mañana", 01, 2023), 
(02, "The Fame", 02, 2008), 
(03, "Maelo...El Unico", 03, 1974), 
(04, "Scorpion", 04, 2018 ),
(05, "Viva el Perreo", 05, 2020 );

INSERT INTO tracks (track_id, title, album_id) VALUES
(01, "MONACO", 01), 
(02, "CYBERTRUCK", 01), 
(03, "VUELVE CANDY B", 01), 
(04, "Poker Face", 02), 
(05, "Paparazzi", 02), 
(06, "LoveGame", 02), 
(07, "El Nazareno", 03), 
(08, "Las Caras Lindas", 03), 
(09, "Traigo de todo", 03), 
(10, "God''s Plan", 04), 
(11, "Nice for What", 04), 
(12, "8 out of 10", 04), 
(13, "Se Acabo la Cuarentena", 05), 
(14, "Reggaeton H", 05), 
(15, "Toxicos", 05);

INSERT INTO listens (listen_id, user_id, track_id, listen_time) VALUES

(01, 01, 01, "10:00"),
(02, 01, 02, "3:30"),
(03, 01, 03, "9:00"),
(04, 01, 04, "5:00"),
(05, 01, 05, "9:25"),
(06, 01, 06, "8:30"),

(07, 02, 04, "7:00"),
(08, 02, 01, "6:30"),
(09, 02, 02, "8:00"),
(10, 02, 05, "9:00"),
(11, 02, 03, "9:25"),
(12, 02, 09, "4:25"),


(13, 03, 01, "12:25"),
(14, 03, 11, "7:25"),
(15, 03, 15, "9:25"),
(16, 03, 13, "2:25"),
(17, 03, 14, "8:25"),

(18, 04, 01, "1:25"),
(19, 04, 10, "9:25"),
(20, 04, 15, "2:25"),
(21, 04, 07, "7:25"),
(22, 04, 03, "10:25"),


(23, 05, 05, "9:00"),
(24, 05, 11, "8:00"),
(25, 05, 07, "2:25"),
(26, 05, 06, "8:50"),
(27, 05, 04, "10:00"),


(28, 01, 03, "1:25"),
(29, 02, 02, "8:25"),
(30, 03, 04, "7:25");

''')

print("Sample data inserted.")

Sample data inserted.


## Part 3 — SQL Challenge Questions

Write SQL queries to answer each question.
Each cell should return a table.

### Q1. List all users.

In [124]:

run_or_todo('''
Select * FROM users;''', label="Q1")

   user_id              name
0        1  Raymond Santiago
1        2      Eric Vicente
2        3      Betzy Flores
3        4      Maria Rivera
4        5      Camila Nunez
5        6           Joe Doe

   user_id              name
0        1  Raymond Santiago
1        2      Eric Vicente
2        3      Betzy Flores
3        4      Maria Rivera
4        5      Camila Nunez
5        6           Joe Doe

### Q2. List all artists.

In [125]:

run_or_todo('''
SELECT * FROM artists;
''', label="Q2")

   artist_id            name
0          1       Bad Bunny
1          2       Lady Gaga
2          3   Ismael Rivera
3          4           Drake
4          5  Jowell y Randy

   artist_id            name
0          1       Bad Bunny
1          2       Lady Gaga
2          3   Ismael Rivera
3          4           Drake
4          5  Jowell y Randy

### Q3. List all albums with their artist name.

In [126]:

run_or_todo('''
SELECT albums.title, artists.name
FROM albums
JOIN artists
ON albums.artist_id = artists.artist_id;
''', label="Q3")

                               title            name
0  Nadie sabe lo que va pasar mañana       Bad Bunny
1                           The Fame       Lady Gaga
2                   Maelo...El Unico   Ismael Rivera
3                           Scorpion           Drake
4                     Viva el Perreo  Jowell y Randy

                               title            name
0  Nadie sabe lo que va pasar mañana       Bad Bunny
1                           The Fame       Lady Gaga
2                   Maelo...El Unico   Ismael Rivera
3                           Scorpion           Drake
4                     Viva el Perreo  Jowell y Randy

### Q4. List all tracks with their album title and artist name.

In [127]:

run_or_todo('''
SELECT tracks.title, albums.title, artists.name
FROM tracks
JOIN albums
ON tracks.album_id = albums.album_id
JOIN artists
ON albums.artist_id = artists.artist_id;
''', label="Q4")

                     title                              title            name
0                   MONACO  Nadie sabe lo que va pasar mañana       Bad Bunny
1               CYBERTRUCK  Nadie sabe lo que va pasar mañana       Bad Bunny
2           VUELVE CANDY B  Nadie sabe lo que va pasar mañana       Bad Bunny
3               Poker Face                           The Fame       Lady Gaga
4                Paparazzi                           The Fame       Lady Gaga
5                 LoveGame                           The Fame       Lady Gaga
6              El Nazareno                   Maelo...El Unico   Ismael Rivera
7         Las Caras Lindas                   Maelo...El Unico   Ismael Rivera
8           Traigo de todo                   Maelo...El Unico   Ismael Rivera
9              God''s Plan                           Scorpion           Drake
10           Nice for What                           Scorpion           Drake
11             8 out of 10                           Scorpion           Drake
12  Se Acabo la Cuarentena                     Viva el Perreo  Jowell y Randy
13             Reggaeton H                     Viva el Perreo  Jowell y Randy
14                 Toxicos                     Viva el Perreo  Jowell y Randy

                     title                              title            name
0                   MONACO  Nadie sabe lo que va pasar mañana       Bad Bunny
1               CYBERTRUCK  Nadie sabe lo que va pasar mañana       Bad Bunny
2           VUELVE CANDY B  Nadie sabe lo que va pasar mañana       Bad Bunny
3               Poker Face                           The Fame       Lady Gaga
4                Paparazzi                           The Fame       Lady Gaga
5                 LoveGame                           The Fame       Lady Gaga
6              El Nazareno                   Maelo...El Unico   Ismael Rivera
7         Las Caras Lindas                   Maelo...El Unico   Ismael Rivera
8           Traigo de todo                   Maelo...El Unico   Ismael Rivera
9              God''s Plan                           Scorpion           Drake
10           Nice for What                           Scorpion           Drake
11             8 out of 10                           Scorpion           Drake
12  Se Acabo la Cuarentena                     Viva el Perreo  Jowell y Randy
13             Reggaeton H                     Viva el Perreo  Jowell y Randy
14                 Toxicos                     Viva el Perreo  Jowell y Randy

### Q5. Show all listening events with user name, track title, and timestamp.

In [128]:

run_or_todo('''
SELECT users.name, tracks.title, listens.listen_time
FROM listens
JOIN users ON listens.user_id = users.user_id
JOIN tracks ON listens.track_id = tracks.track_id;
''', label="Q5")

                name                   title listen_time
0   Raymond Santiago                  MONACO       10:00
1   Raymond Santiago              CYBERTRUCK        3:30
2   Raymond Santiago          VUELVE CANDY B        9:00
3   Raymond Santiago              Poker Face        5:00
4   Raymond Santiago               Paparazzi        9:25
5   Raymond Santiago                LoveGame        8:30
6       Eric Vicente              Poker Face        7:00
7       Eric Vicente                  MONACO        6:30
8       Eric Vicente              CYBERTRUCK        8:00
9       Eric Vicente               Paparazzi        9:00
10      Eric Vicente          VUELVE CANDY B        9:25
11      Eric Vicente          Traigo de todo        4:25
12      Betzy Flores                  MONACO       12:25
13      Betzy Flores           Nice for What        7:25
14      Betzy Flores                 Toxicos        9:25
15      Betzy Flores  Se Acabo la Cuarentena        2:25
16      Betzy Flores             Reggaeton H        8:25
17      Maria Rivera                  MONACO        1:25
18      Maria Rivera             God''s Plan        9:25
19      Maria Rivera                 Toxicos        2:25
20      Maria Rivera             El Nazareno        7:25
21      Maria Rivera          VUELVE CANDY B       10:25
22      Camila Nunez               Paparazzi        9:00
23      Camila Nunez           Nice for What        8:00
24      Camila Nunez             El Nazareno        2:25
25      Camila Nunez                LoveGame        8:50
26      Camila Nunez              Poker Face       10:00
27  Raymond Santiago          VUELVE CANDY B        1:25
28      Eric Vicente              CYBERTRUCK        8:25
29      Betzy Flores              Poker Face        7:25

                name                   title listen_time
0   Raymond Santiago                  MONACO       10:00
1   Raymond Santiago              CYBERTRUCK        3:30
2   Raymond Santiago          VUELVE CANDY B        9:00
3   Raymond Santiago              Poker Face        5:00
4   Raymond Santiago               Paparazzi        9:25
5   Raymond Santiago                LoveGame        8:30
6       Eric Vicente              Poker Face        7:00
7       Eric Vicente                  MONACO        6:30
8       Eric Vicente              CYBERTRUCK        8:00
9       Eric Vicente               Paparazzi        9:00
10      Eric Vicente          VUELVE CANDY B        9:25
11      Eric Vicente          Traigo de todo        4:25
12      Betzy Flores                  MONACO       12:25
13      Betzy Flores           Nice for What        7:25
14      Betzy Flores                 Toxicos        9:25
15      Betzy Flores  Se Acabo la Cuarentena        2:25
16      Betzy Flores             Reggaeton H        8:25
17      Maria Rivera                  MONACO        1:25
18      Maria Rivera             God''s Plan        9:25
19      Maria Rivera                 Toxicos        2:25
20      Maria Rivera             El Nazareno        7:25
21      Maria Rivera          VUELVE CANDY B       10:25
22      Camila Nunez               Paparazzi        9:00
23      Camila Nunez           Nice for What        8:00
24      Camila Nunez             El Nazareno        2:25
25      Camila Nunez                LoveGame        8:50
26      Camila Nunez              Poker Face       10:00
27  Raymond Santiago          VUELVE CANDY B        1:25
28      Eric Vicente              CYBERTRUCK        8:25
29      Betzy Flores              Poker Face        7:25

### Q6. How many tracks does each album contain?

In [129]:

run_or_todo('''
SELECT albums.title, COUNT(tracks.track_id) AS track_count
FROM albums
JOIN tracks ON tracks.album_id = albums.album_id
GROUP BY albums.album_id, albums.title
''', label="Q6")

                               title  track_count
0  Nadie sabe lo que va pasar mañana            3
1                           The Fame            3
2                   Maelo...El Unico            3
3                           Scorpion            3
4                     Viva el Perreo            3

                               title  track_count
0  Nadie sabe lo que va pasar mañana            3
1                           The Fame            3
2                   Maelo...El Unico            3
3                           Scorpion            3
4                     Viva el Perreo            3

### Q7. How many listens does each track have?

In [130]:

run_or_todo('''
SELECT tracks.title, COUNT(listens.listen_id) AS listen_count
FROM tracks
LEFT JOIN listens ON listens.track_id = tracks.track_id
GROUP BY tracks.track_id, tracks.title;
''', label="Q7")

                     title  listen_count
0                   MONACO             4
1               CYBERTRUCK             3
2           VUELVE CANDY B             4
3               Poker Face             4
4                Paparazzi             3
5                 LoveGame             2
6              El Nazareno             2
7         Las Caras Lindas             0
8           Traigo de todo             1
9              God''s Plan             1
10           Nice for What             2
11             8 out of 10             0
12  Se Acabo la Cuarentena             1
13             Reggaeton H             1
14                 Toxicos             2

                     title  listen_count
0                   MONACO             4
1               CYBERTRUCK             3
2           VUELVE CANDY B             4
3               Poker Face             4
4                Paparazzi             3
5                 LoveGame             2
6              El Nazareno             2
7         Las Caras Lindas             0
8           Traigo de todo             1
9              God''s Plan             1
10           Nice for What             2
11             8 out of 10             0
12  Se Acabo la Cuarentena             1
13             Reggaeton H             1
14                 Toxicos             2

### Q8. How many listens has each user made?

In [131]:

run_or_todo('''
SELECT users.name, COUNT(listens.listen_id) AS listen_count
FROM users
LEFT JOIN listens ON listens.user_id = users.user_id
GROUP BY users.user_id, users.name;
''', label="Q8")

               name  listen_count
0  Raymond Santiago             7
1      Eric Vicente             7
2      Betzy Flores             6
3      Maria Rivera             5
4      Camila Nunez             5
5           Joe Doe             0

               name  listen_count
0  Raymond Santiago             7
1      Eric Vicente             7
2      Betzy Flores             6
3      Maria Rivera             5
4      Camila Nunez             5
5           Joe Doe             0

### Q9. Which tracks have been listened to more than 3 times?

In [132]:

run_or_todo('''
SELECT tracks.title, COUNT(listens.listen_id) AS listen_count
FROM listens
Join tracks on listens.track_id = tracks.track_id
GROUP BY tracks.track_id, tracks.title
HAVING COUNT(listens.listen_id) > 3;
''', label="Q9")

            title  listen_count
0          MONACO             4
1  VUELVE CANDY B             4
2      Poker Face             4

            title  listen_count
0          MONACO             4
1  VUELVE CANDY B             4
2      Poker Face             4

### Q10. Which album has the most total listens?

In [133]:

run_or_todo('''
SELECT albums.title, COUNT(listens.listen_id) AS listen_count
FROM listens
JOIN tracks ON listens.track_id = tracks.track_id
JOIN albums ON tracks.album_id = albums.album_id
GROUP BY albums.album_id, albums.title
ORDER BY listen_count DESC
LIMIT 1;
''', label="Q10")

                               title  listen_count
0  Nadie sabe lo que va pasar mañana            11

                               title  listen_count
0  Nadie sabe lo que va pasar mañana            11

### Q11. Which artist has the most total listens?

In [134]:

run_or_todo('''
SELECT artists.name, COUNT(listens.listen_id) AS total_listens
FROM listens
JOIN tracks ON listens.track_id = tracks.track_id
JOIN albums ON tracks.album_id = albums.album_id
JOIN artists ON albums.artist_id = artists.artist_id
GROUP BY artists.artist_id, artists.name
ORDER BY total_listens DESC
LIMIT 1;
''', label="Q11")

        name  total_listens
0  Bad Bunny             11

        name  total_listens
0  Bad Bunny             11

### Q12. What is the average number of listens per user?

In [135]:

run_or_todo('''
SELECT AVG(listen_count) AS avg_listens
FROM(
    SELECT users.user_id, COUNT(listens.listen_id) AS listen_count
    FROM users
    LEFT JOIN listens ON listens.user_id = users.user_id
    GROUP BY users.user_id
) AS Q12;
''', label="Q12")

   avg_listens
0          5.0

   avg_listens
0          5.0

### Q13. Which users have never listened to a track?

In [136]:

run_or_todo('''
SELECT users.name
FROM users
LEFT JOIN listens ON listens.user_id = users.user_id
WHERE listens.user_id IS NULL;
''', label="Q13")

      name
0  Joe Doe

      name
0  Joe Doe

### Q14. Show the top 5 most-listened-to tracks.

In [137]:

run_or_todo('''
SELECT tracks.title, COUNT(listens.listen_id) AS listen_count
FROM listens
JOIN tracks ON listens.track_id = tracks.track_id
GROUP BY tracks.track_id, tracks.title
ORDER BY listen_count DESC
LIMIT 5
''', label="Q14")

            title  listen_count
0          MONACO             4
1  VUELVE CANDY B             4
2      Poker Face             4
3      CYBERTRUCK             3
4       Paparazzi             3

            title  listen_count
0          MONACO             4
1  VUELVE CANDY B             4
2      Poker Face             4
3      CYBERTRUCK             3
4       Paparazzi             3

### Q15. Explain why the listens table cannot be merged into users or tracks.

In [138]:

run_or_todo('''
SELECT TODO
''', label="Q15")

Q15: TODO — write the SQL, then re-run this cell.

The listen table connects users to tracks, and users can listen to as many songs as they want; each track can be listened to by as many users as possible. Each listen contains its own timestamp, which cannot be stored with users or tracks tables. Keeping listens as a separate table allows for each listen to be in its own row.


## Part 4 — Reflection

Answer in 3–5 sentences.

In [139]:

reflection = """
The easiest part was doing simple tasks and creating subsetted tables to describe the 
music data. The hardest and most tedious parts were making the original tables and feeling 
like I approached the problem correctly. This assignment helped me understand more about what happens behind the scenes, but most importantly, what approaches I 
should take depending on the objective.

"""

print(reflection)

The easiest part was doing simple tasks and creating subsetted tables to describe the
music data. The hardest and most tedious parts were making the original tables and feeling
like I approached the problem correctly. This assignment helped me understand more about what happens behind the scenes, but most importantly, what approaches I
should take depending on the objective.


## Grading Rubric (100 points)

### Database Design (30 pts)
- Correct tables created (10)
- Correct primary keys (10)
- Correct foreign keys & relationships (10)

### Data Insertion (15 pts)
- Meets minimum data requirements
- Referential integrity preserved

### SQL Queries (40 pts)
- Correct logic & joins (25)
- Proper GROUP BY / HAVING usage (10)
- Clean, readable queries (5)

### Reflection & Notebook Quality (15 pts)
- Reflection completed (5)
- All cells run without error (10)


## Submission Checklist

- All TODOs replaced
- All cells run successfully
- Outputs visible
- Notebook saved
- Git URL submitted in Canvas